### ISSUE TITLE
Chinese characters are garbled

### ISSUE THREAD

**Issue by zzzzzy404** [AvaloniaUI/Avalonia.HtmlRenderer#31]
![image](https://github.com/AvaloniaUI/Avalonia.HtmlRenderer/assets/95996749/4e1f1c37-91c3-42c1-af49-67226835db0e)

This is one of my tests, the red box is Chinese, but the characters are garbled
This is bug or my fault?
How to fixed it？
Thinks for your time.

**Comment by maxkatz6** [comment]
You probably need to setup a font with Chinese glyphs. cc @Gillibald

**Comment by maxkatz6** [comment]
It seems to be NetSparkle dialog, which uses 0.10 version.
Closing as expected https://github.com/NetSparkleUpdater/NetSparkle/blob/develop/src/NetSparkle.UI.Avalonia/UpdateAvailableWindow.xaml#L80

This library should be updated to 11.0 or you can use your own dilaogs with netsparkle (instead of NetSparkle.UI.Avalonia package).
