### ISSUE TITLE
HtmlPanel control

### ISSUE THREAD

**Issue by aplocher** [AvaloniaUI/Avalonia.HtmlRenderer#4]
In HtmlControl.cs there is a large comment referencing HtmlLabel and HtmlPanel.  There doesn't appear to be an HtmlPanel, in fact the only public class with a public constructor appears to be HtmlLabel.  Is there any way to render chunk of HTML in a panel with Avalonia?

I'm looking for a cross platform equivalent to the System.Windows.(Controls|Forms).WebBrowser control - preferably one that doesn't require a Chrome process to be loaded up (which I believe is how CefGlue works, if I'm not mistaken). Avoiding the Chrome process was my primary reason for choosing Avalonia over Electron for my project.

Thanks! :)

PS - are there any implementation examples/demos or documentation for this that I can reference?  thx again

PS Again - when I say "WebBrowser" equivalent I should clarify that it doesn't need to be used for anything complex.  I'm essentially rendering Markdown to HTML using Markdig.  So it will be some headers, bold, italic, links, etc.  No crazy layout or anything.

**Comment by kekekeks** [comment]
I think HtmlPanel wasn't ported from [WPF version](https://github.com/ArthurHub/HTML-Renderer/blob/e0a2d1702aae5a4f267cc60d847c2c64c1a5b0bc/Source/HtmlRenderer.WPF/HtmlPanel.cs) for some reason. Should be possible to do.

>are there any implementation examples/demos or documentation for this that I can reference? thx again

There was a demo in our old control catalog before HtmlRenderer was moved to a separate repo, can't find it now.

Unfortunately our HtmlRenderer port wasn't well-maintained since 2015, I think. We might need a rewrite of the adapters since they have quite a bit of stuff hardcoded due to the lack of the needed APIs at that point.

**Comment by apavelm** [comment]
Hi,
I didn't find an appropriate section/sub-project and probably this topic matches most.
Using an internal in-app browser is a big pain for WPF, especially for cross-platform applications.
I don't consider "WebBrowser" as an in-app browser because of it outdated and doesn't support/visualize HTML/CSS/JS good.
For example, a simple case with external OAuth2 auth via "Auth0" service. Usage of something like CEF will increase the size of the app up to 160MB or more, or even more. Also, it is platform and architecture-specific. No special additional features required, just correct visualization of HTML with CSS/JS to show Auth0 login page.

@kekekeks Nikita, could you please advice something for this purpose to be used among with Avalonia? I would very much appreciate if you could help with this. Thank you.

**Comment by kekekeks** [comment]
With "don't ship 160MB of an actual browser" requirement you probably want something like [WebWindow](https://blog.stevensanderson.com/2019/11/18/2019-11-18-webwindow-a-cross-platform-webview-for-dotnet-core/) library that attempts to reuse existing platform webview capabilities. Which means only supporting Windows 10 as the minimum Windows version and depending on GTK on Linux.

**Comment by apavelm** [comment]
Unfortunately, **WebWindow** is unworkable at all. Even their "Hello World" sample doesn't work.
re 160MB I told about CEF. WebWindow looks interesting, but...

**Comment by maxkatz6** [comment]
Done
